# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - TimelessHorror

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://github.com/jawshygg/timelesshorror/
        username: ${{ secrets.AzureAppService_ContainerUsername_51675469128c44bd94c11b6f490722ed }}
        password: ${{ secrets.AzureAppService_ContainerPassword_605fde8314074f0cb17e3134002f0577 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: github.com/jawshygg/timelesshorror/${{ secrets.AzureAppService_ContainerUsername_51675469128c44bd94c11b6f490722ed }}/https:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'TimelessHorror'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_5c36b0eea11a4101a7c26022f6ae5f23 }}
        images: 'github.com/jawshygg/timelesshorror/${{ secrets.AzureAppService_ContainerUsername_51675469128c44bd94c11b6f490722ed }}/https:${{ github.sha }}'
